# Generated by Django 5.0.2 on 2024-02-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fch_visita', models.DateTimeField(auto_now_add=True)),
                ('ip_visita', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion_visita', models.CharField(blank=True, max_length=255, null=True)),
                ('dispositivo_visitante', models.CharField(blank=True, max_length=255, null=True)),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('sistema_operativo', models.CharField(blank=True, max_length=255, null=True)),
                ('slug_visita', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'HomepageVisitas',
                'ordering': ['id'],
            },
        ),
    ]
